# fly.toml app configuration file generated for recommendations-nodjs on 2024-12-14T21:10:47+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recommendations-nodjs'
primary_region = 'bom'

[build]



[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
